apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    run: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx:1.22.1
    ports:
    - containerPort: 80
      


# kubectl run nginx-pod --image=nginx:1.22.1 --port=80
# kubectl run nginx-pod --image=nginx:1.22.1 --port=80 \
  # dry-run=client -o yaml > nginx-pod.yaml