apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTZXVFlHVkRqSzZURUVxZ2FzV2ZTMXpTCnRKMkRrWi9hZVdremFoS2dYOWdEZUF3amFXcWhwOVVkd2Z2eTk5d0drelUvN0xzVFNpL1VXMndMSGZEd2ZHZGIKc2RRRUl2NHFmVm1ZRHR1R1FZS2tZblFMdWoxdnZMY1VDVGFLaE1TbWFBTklneFV1T3VnTEkrbkYzS2RucHRyVgpWakVZMDZ4YVgvVHp5SEdjUjkrMmpXREU0WFgzZHN0dlJLaFQrL2s2QzNoSmN3N2l2eGNoSTVoaUNvUjJCMXYyClhIc2NrdUZXYVN0djFOZFluaXNOS2grYlVNZ3EvOG9TSFMxUzJBb0NMQ2tWWGZWc25MdnZkaWcyaFBvYjhoUFAKM0hTVWRrQ0k3LzR1M3dpV0tQdCtKNnU5Z3JIa0NkZGN6ekRXNzU5VktQM3RlSjFKaStOTGROZWNRbEIxYXdJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBUk9IUEpFNXlBaTJRTW42bUUwcFQ0RlEvM1lOc1NlCjN3VlIvK0d2Z3BxNmI4L3FucEJib2pIM3pjLzhCblErNXlOVStibkZPSHFwUno2dVdxWGlqTThGbEZONGpPYmcKdzhIL0NXemZ2RzZQWHlValF0S0dKZXJ4S2NpNi9YYVBlY3B3TTdPS1NvdjdpVzFzeFBnTkdKbkhoTFlvVVpucQpFQjdmTlhXWmp5QkRTR0RXY2Q4Sm9GV0craDFLTkhTb2FGdGY3Mlk5ellyU25QaHZPbFlGcXlGdWZ6NVlDZ3BIClIzclI4Um1zL1N6Nm44VkdQZk1nQ3ArdUN0RmVQanN3TWtHT01MTzZlV2V4ZldrVEtsbEFHOEFsUHM2OWw0cTUKRkV6UnNvYzl3WlRHYk5ocWFZL3ZmNjNva29DMUpXbDE4WG9Hc3h1aFhaTXNDcisrQWk1dmdtVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
