apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd1BSbEdrK1E0WmJTeUladmlUUlVwUXorCjNCM2sySnQwWmJ3QWJvWEd6U1JMQlRVLzh6bm9QVElTUUQxUEgxVlV6MEM4UThnelRpbFdNMXFhSjhsRFU5QnEKdjZEdlRiZWl6TnZmbU1XWDBEeHk3NWRSdXIyODdlTUpVVDNEMFhicU51NC8vSC9HcFY5R2RTd1JkR3M2eVhhdQoxb2pGOWlNTWVQSnBiWDB0REt5blk0RThoUWRaK0o3aklKM3NUWjd1Q0I4TUdzUS9DM09oclhvRks1b3RVNlpYCjVyRzlRemxLTmsyTUNKalY4NDdmV2E2b0Ewb05sYTh3YTFaUXRVaERVYTZsNEV3bXhOb2Q0Zms5eC9WUWVUSG4KdUhtTFAxRnVPenY0MlFjMGh4QzJqTVdMQ3Y2Vk4wUGZQbEI1bVRhdjdKam1zb09pN28reFkvME8yQWFEK3dJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKL1kva2lYelpLb3RJN2hHSWV3M1U3Q2wraUw1YUIzCm1wRm05WE4yL3BnUDBQeThweUc2bTR5ZzN0bmREQzBXV2IzQmdRbFQ3dHljV3dTUEZ1WFk1TWhTVDVJblpxUGsKRGVqT3ZlZjh0ejRHb2c1bkx6MHp5SUsxdFF2Rnl4UGFiTFNYb1pORFo5ZTMzQW45RURYZTFmeFlLVHRKazVtMwpvL0JZZzc3V3BCbWhVUjNEd2ZPZ2l0ZjMyM2xWK0tWSG5IZE92bHdyTjNCODFtZ0dwczlmdDMvVWZ4ZWdBdWlyCjF3RVc4WFh5Z1F4UUU0S0pZTGs1R1BCZlF0aEI5Y2NqTjRNVWorN1pKb01OekNEcW0yc3BabEE4MU5meDFWcXkKY2JIUEZGby9PNzRVVGUwM1NuZTNoamFPUlRXamtWaHZqYzBXSTU2WnFaYzlJcWo4aHpmODVZTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
