apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-gp2


  # This PVC requests a 10Gi storage volume that can be mounted read-write by a single node, using the ebs-gp2 StorageClass(for example, AWS EBS).
  # Kubernetes either binds this PVC to an existing PV with compatible parameters or dynamically provisions a new one. 
  # Once bound, pods can mount the PVC as a volume