apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
    - name: vol
      emptyDir: {}
  containers:
    - name: busy
      image: busybox:1.28
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - mountPath:  /data/demo
          name: vol
      securityContext:
        allowPrivilegeEscalation: false