apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-web
  name: blue-web
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue-web
    spec:
      volumes:
      - name: web-config
        configMap:
          name: blue-web-cm
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: web-config
status: {}



# kubectl create configmap green-web-cm --from-file=./configmapsAndSecrets/indexblue.html